
[back]
	#Leech Scabbard healing rate as percentage of damage dealt
	#Range: 0.0 ~ 100.0
	leechScabbardHealFactor = 0.25

[bracelet]
	#This value determines how many seconds you will receive a stealth effect once
	#Range: > 1
	hiddenBraceletEffectDuration = 7

[charm]
	#This value determines the maximum damage increase
	#Range: 0.0 ~ 2.147483647E9
	holySwordMaxAddDamage = 0.5
	#This value determines how much life you lose and how much damage you inflict once
	#Range: 1.0 ~ 2.147483647E9
	holySwordLostLifeAddDamage = 1.0
	#This value determines how many ticks remove negative effects once
	#Range: > 1
	angelHeartRemoveInterval = 600
	#This value determines how many ticks restore health once
	#Range: > 1
	angelHeartBloodInterval = 30
	#This value determines how much health is restored at once
	#Range: > 1
	angelHeartHealAmount = 1
	#This value determines how much health is greater than the current one in order to trigger damage reduction
	#Range: 0.01 ~ 1.0
	cursedProtectorJudgingLife = 0.35
	#This value determines its damage reduction amount
	#Range: 0.01 ~ 1.0
	cursedProtectorReduceInjury = 0.25
	#This value determines the critical hit rate increased by each enchantment
	#Range: 0.01 ~ 1.0
	cursedTalismanCritRateAdd = 0.04
	#This value determines the critical hit damage increased by each enchantment
	#Range: 0.01 ~ 1.0
	cursedTalismanCritDamageAdd = 0.08

[curse]
	#When true, when the player enters the world, the accessory will be directly worn in the accessory bar
	catastropheScrollStart = false
	#This value determines how much explosive damage you will receive due to the Chaos Curse
	#Range: 0.01 ~ 2.147483647E9
	catastropheScrollExplosionDamage = 0.75
	#This value determines how much other damage you will receive due to the Chaos Curse
	#Range: 0.01 ~ 2.147483647E9
	catastropheScrollOtherDamage = 0.5
	#This value determines how much damage is negatively affected
	#Range: 0.01 ~ 1.0
	catastropheScrollEndCurseDamage = 0.25
	#This value determines how much your damage will be reduced due to the Origin Curse
	#Range: 0.01 ~ 1.0
	catastropheScrollOriginCurseDamage = 0.5
	#This value determines how many enemies with maximum health you need to defeat in order to possibly drop it
	#Range: > 1
	etchingOfLifeDropCondition = 499

