
[options]
	#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
	preventdeath = true
	#Message that displays when Teleport is blocked
	blockedmessage = "The icy phoenix has sealed off this dimension."
	#Title for the Advancements
	craftedmessage = "%dim% To unlock!"
	#Description for the Advancements
	description = "Translate it to English: Obtain a %item%."
	#Comma seperated list of items that when crafted unlock the corresponding dimension
	craftitems = "kubejs:tf_catalytic_stone,ad_astra:tier_4_rocket,ad_astra:tier_2_rocket,ad_astra:tier_4_rocket"
	#Comma seperated list of Dimension Resource Names
	dimresname = "twilightforest:twilight_forest,the_forgotten_dimensions:perma_frost,rats:ratlantis,the_forgotten_dimensions:ryumsky"
	#Comma seperated list of Dimension Display Names
	dimnames = "twilightforest,theforgottendimensions,ratlantis,ryumsky"

