
["Save Settings"]
	#Where to save the panoramas
	panoramaSaveFolder = ".\\panoramas"
	#The resolution of one image in the panorama. Increasing the resolution will lead to higher quality images but at the cost of performance and storage space
	#Range: 240 ~ 8192
	renderResolution = 1920

["Main menu"]
	#Whether to use custom panoramas on the main menu
	useCustomPanoramas = true

